/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: iturrospe (https://sketchfab.com/iturrospe)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/basketball-4ed71d73c43b495eb784156acc32ba46
title: BASKETBALL
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { useSphere } from '@react-three/cannon'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    mesh_1: THREE.Mesh
    mesh_0: THREE.Mesh
  }
  materials: {
    BBALL_RIM: THREE.MeshStandardMaterial
    BBALL_PRINCIPAL: THREE.MeshStandardMaterial
  }
}

export default function Basketball(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  // useFrame((state, delta) => (group.current.rotation.x += 0.01))

  const { nodes, materials } = useGLTF('./models/basketball/scene.gltf') as GLTFResult

  // const [ref, api] = useSphere(() => ({ mass: 1 }))


  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.mesh_1.geometry} material={materials.BBALL_RIM} />
          <mesh geometry={nodes.mesh_0.geometry} material={materials.BBALL_PRINCIPAL} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/basketball/scene.gltf')
